[package]
name = "surge-ping"
version = "0.7.0"
authors = ["kolapapa <kolapapa2021@gmail.com>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/kolapapa/surge-ping"
repository = "https://github.com/kolapapa/surge-ping"
description = "Asynchronous ICMP ping library"
keywords = ["tokio", "icmp", "ping"]
categories = ["network-programming", "asynchronous"]

[dependencies]
parking_lot = "0.12.0"
pnet_packet = "0.30"
rand = "0.8.5"
socket2 = { version = "0.4.4", features = ["all"] }
thiserror = "1.0.31"
tokio = { version = "1.18", features = ["time", "sync"] }
tracing = "0.1.34"


[dev-dependencies]
structopt = "0.3.26"
pretty_env_logger = "0.4.0"
tokio = { version = "1", features = ["full"] }
futures = "0.3.21"

[[example]]
name = "simple"

[[example]]
name = "cmd"

[[example]]
name = "multi_ping"
